---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.68.1
    hooks:
      - id: terraform_validate
        args:
          - --init-args=-backend=false
      - id: terraform_fmt
      - id: terraform_docs
