---

name: Terraform Apply Workflow

on:
  public
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS Region to use"
        required: true
      aws_bucket_name:
        description: "AWS S3 Bucket to store TF States"
        required: true
      aws_bucket_key_path:
        description: "AWS S3 Bucket Key Path to store state"
        required: true
        default: "redis.tfstate"
      aws_access_key_id:
        description: "Access key id to access AWS"
        required: true
      aws_secret_access_key:
        description: "Secret access key to access AWS"
        required: true
      aws_instance_type:
        description: "Instance type to be created"
        required: true
        default: "t2.micro"

jobs:
  plan_and_apply:
    name: Plan and Apply
    runs-on: ubuntu-latest
    needs:
      - lint
      - checkov
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ github.event.inputs.aws_region }}
          aws-access-key-id: ${{ github.event.inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ github.event.inputs.aws_secret_access_key }}

      - name: Install Ansible
        run: pip3 install "ansible==2.9.16"

      - name: Run bucket prepare script
        run: |
          sed -i "s/BUCKET_NAME/${{ github.event.inputs.aws_bucket_name }}/g" provisioning/prepare_bucket.sh
          sed -i "s/AWS_REGION/${{ github.event.inputs.aws_region }}/g" provisioning/prepare_bucket.sh
          chmod +x provisioning/prepare_bucket.sh
          bash provisioning/prepare_bucket.sh

      - name: Pass input variables
        run: |
          sed -i "s/BUCKET_NAME/${{ github.event.inputs.aws_bucket_name }}/g" terraform.tf
          sed -i "s/AWS_REGION/${{ github.event.inputs.aws_region }}/g" terraform.tf
          sed -i "s/BUCKET_KEY_PATH/${{ github.event.inputs.aws_bucket_key_path }}/g" terraform.tf
          sed -i "s/AWS_REGION/${{ github.event.inputs.aws_region }}/g" variables.tf
          sed -i "s/AWS_INSTANCE_TYPE/${{ github.event.inputs.aws_instance_type }}/g" variables.tf

      - name: Initialize Terraform
        run: terraform init -input=false

      - name: Plan Terraform
        id: plan
        run: terraform plan -input=false

      - name: Apply Terraform
        if: steps.plan.outcome == 'success'
        id: apply
        run: terraform apply -input=false -auto-approve
